name: Build Flutter APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Unpack and build
      run: |
        unzip xiaomi_camera.zip -d project_extracted
        cd project_extracted/xiaomi_camera
        flutter create --platforms android .
        flutter pub upgrade --major-versions
        flutter build apk --release
        cp build/app/outputs/flutter-apk/app-release.apk ../../app-release.apk

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: app-release.apk
        
